
services:
  web:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
